/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 1
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_EQ = 2,
  anon_sym_COLON = 3,
  anon_sym_Input = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  sym_param_def = 7,
  anon_sym_Const = 8,
  anon_sym_Reference = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_CARET = 14,
  anon_sym_LT_GT = 15,
  anon_sym_LT = 16,
  anon_sym_LT_EQ = 17,
  anon_sym_GT = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_COMMA = 20,
  sym_identifier = 21,
  aux_sym_number_token1 = 22,
  aux_sym_number_token2 = 23,
  aux_sym_number_token3 = 24,
  anon_sym_DQUOTE = 25,
  aux_sym_string_token1 = 26,
  aux_sym_string_token2 = 27,
  sym_source_file = 28,
  sym_statement = 29,
  sym_assignment = 30,
  sym_declaration = 31,
  sym_type_def = 32,
  sym_input_def = 33,
  sym_const_def = 34,
  sym_reference_def = 35,
  sym_expression = 36,
  sym_parenthesized_expression = 37,
  sym_binary_expression = 38,
  sym_unary_expression = 39,
  sym_function_call = 40,
  sym_number = 41,
  sym_string = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_function_call_repeat1 = 44,
  aux_sym_string_repeat1 = 45,
  alias_sym_unary_operator = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_Input] = "Input",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_param_def] = "param_def",
  [anon_sym_Const] = "Const",
  [anon_sym_Reference] = "Reference",
  [anon_sym_PLUS] = "binary_operator",
  [anon_sym_DASH] = "binary_operator",
  [anon_sym_STAR] = "binary_operator",
  [anon_sym_SLASH] = "binary_operator",
  [anon_sym_CARET] = "binary_operator",
  [anon_sym_LT_GT] = "binary_operator",
  [anon_sym_LT] = "binary_operator",
  [anon_sym_LT_EQ] = "binary_operator",
  [anon_sym_GT] = "binary_operator",
  [anon_sym_GT_EQ] = "binary_operator",
  [anon_sym_COMMA] = ",",
  [sym_identifier] = "identifier",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_declaration] = "declaration",
  [sym_type_def] = "type_def",
  [sym_input_def] = "input_def",
  [sym_const_def] = "const_def",
  [sym_reference_def] = "reference_def",
  [sym_expression] = "expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_function_call] = "function_call",
  [sym_number] = "number",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_unary_operator] = "unary_operator",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_Input] = anon_sym_Input,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_param_def] = sym_param_def,
  [anon_sym_Const] = anon_sym_Const,
  [anon_sym_Reference] = anon_sym_Reference,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_PLUS,
  [anon_sym_SLASH] = anon_sym_PLUS,
  [anon_sym_CARET] = anon_sym_PLUS,
  [anon_sym_LT_GT] = anon_sym_PLUS,
  [anon_sym_LT] = anon_sym_PLUS,
  [anon_sym_LT_EQ] = anon_sym_PLUS,
  [anon_sym_GT] = anon_sym_PLUS,
  [anon_sym_GT_EQ] = anon_sym_PLUS,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_identifier] = sym_identifier,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_declaration] = sym_declaration,
  [sym_type_def] = sym_type_def,
  [sym_input_def] = sym_input_def,
  [sym_const_def] = sym_const_def,
  [sym_reference_def] = sym_reference_def,
  [sym_expression] = sym_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_function_call] = sym_function_call,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_unary_operator] = alias_sym_unary_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_param_def] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Reference] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_def] = {
    .visible = true,
    .named = true,
  },
  [sym_input_def] = {
    .visible = true,
    .named = true,
  },
  [sym_const_def] = {
    .visible = true,
    .named = true,
  },
  [sym_reference_def] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_function = 1,
  field_name = 2,
  field_operator = 3,
  field_source = 4,
  field_target = 5,
  field_type = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_source] = "source",
  [field_target] = "target",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_operator, 0},
  [5] =
    {field_function, 0},
  [6] =
    {field_operator, 1},
  [7] =
    {field_source, 2},
  [8] =
    {field_value, 2},
  [9] =
    {field_target, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = alias_sym_unary_operator,
  },
  [5] = {
    [1] = anon_sym_PLUS,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '"', 59,
        '#', 35,
        '(', 39,
        ')', 40,
        '*', 46,
        '+', 44,
        ',', 54,
        '-', 45,
        '.', 23,
        '/', 47,
        ':', 37,
        '<', 50,
        '=', 36,
        '>', 52,
        'C', 15,
        'I', 12,
        'P', 3,
        'R', 6,
        '\\', 2,
        '^', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 2:
      if (lookahead == 'U') ADVANCE(31);
      if (lookahead == 'u') ADVANCE(27);
      if (lookahead == 'x') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 32:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '"', 59,
        '#', 35,
        '(', 39,
        ')', 40,
        '*', 46,
        '+', 44,
        ',', 54,
        '-', 45,
        '.', 23,
        '/', 47,
        ':', 37,
        '<', 50,
        '=', 36,
        '>', 52,
        'C', 15,
        'I', 12,
        'P', 3,
        'R', 6,
        '^', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '"', 59,
        '#', 35,
        '(', 39,
        ')', 40,
        '*', 46,
        '+', 44,
        ',', 54,
        '-', 45,
        '.', 23,
        '/', 47,
        ':', 37,
        '<', 50,
        '=', 36,
        '>', 52,
        '^', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_Input);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_param_def);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_Const);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_Reference);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(51);
      if (lookahead == '>') ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 33},
  [2] = {.lex_state = 33},
  [3] = {.lex_state = 33},
  [4] = {.lex_state = 33},
  [5] = {.lex_state = 33},
  [6] = {.lex_state = 33},
  [7] = {.lex_state = 33},
  [8] = {.lex_state = 33},
  [9] = {.lex_state = 33},
  [10] = {.lex_state = 33},
  [11] = {.lex_state = 33},
  [12] = {.lex_state = 33},
  [13] = {.lex_state = 33},
  [14] = {.lex_state = 33},
  [15] = {.lex_state = 33},
  [16] = {.lex_state = 33},
  [17] = {.lex_state = 33},
  [18] = {.lex_state = 33},
  [19] = {.lex_state = 33},
  [20] = {.lex_state = 33},
  [21] = {.lex_state = 33},
  [22] = {.lex_state = 33},
  [23] = {.lex_state = 33},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 33},
  [26] = {.lex_state = 33},
  [27] = {.lex_state = 33},
  [28] = {.lex_state = 33},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 33},
  [33] = {.lex_state = 33},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 33},
  [39] = {.lex_state = 33},
  [40] = {.lex_state = 33},
  [41] = {.lex_state = 33},
  [42] = {.lex_state = 33},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 33},
  [45] = {.lex_state = 33},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 33},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_Input] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_param_def] = ACTIONS(1),
    [anon_sym_Const] = ACTIONS(1),
    [anon_sym_Reference] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(50),
    [sym_statement] = STATE(33),
    [sym_assignment] = STATE(41),
    [sym_declaration] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(33),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(9), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [25] = 2,
    ACTIONS(17), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(15), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [47] = 3,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(19), 14,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [71] = 2,
    ACTIONS(13), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(9), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [93] = 2,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [115] = 2,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(29), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [137] = 2,
    ACTIONS(35), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [159] = 2,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [181] = 6,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(45), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 9,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [211] = 2,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [233] = 5,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(45), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [261] = 4,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [287] = 4,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [313] = 2,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [335] = 2,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 15,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      sym_identifier,
  [357] = 9,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [392] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [424] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [456] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [488] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [520] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [552] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(14), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [584] = 9,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(45), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(77), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 4,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [618] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [650] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [682] = 7,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(45), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(77), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_identifier,
    ACTIONS(73), 4,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [712] = 8,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_expression,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(5), 6,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_number,
      sym_string,
  [744] = 7,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(45), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(77), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(83), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(73), 4,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [773] = 7,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(45), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(77), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 4,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [801] = 6,
    ACTIONS(87), 1,
      anon_sym_Input,
    ACTIONS(89), 1,
      sym_param_def,
    ACTIONS(91), 1,
      anon_sym_Const,
    ACTIONS(93), 1,
      anon_sym_Reference,
    STATE(39), 1,
      sym_type_def,
    STATE(38), 3,
      sym_input_def,
      sym_const_def,
      sym_reference_def,
  [822] = 5,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      sym_comment,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(32), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(41), 2,
      sym_assignment,
      sym_declaration,
  [840] = 5,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    STATE(32), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(41), 2,
      sym_assignment,
      sym_declaration,
  [858] = 4,
    ACTIONS(69), 1,
      aux_sym_number_token2,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    ACTIONS(67), 2,
      aux_sym_number_token1,
      aux_sym_number_token3,
    STATE(48), 2,
      sym_number,
      sym_string,
  [873] = 3,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      aux_sym_string_repeat1,
    ACTIONS(107), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [884] = 3,
    ACTIONS(109), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      aux_sym_string_repeat1,
    ACTIONS(111), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [895] = 3,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    STATE(35), 1,
      aux_sym_string_repeat1,
    ACTIONS(116), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [906] = 1,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_identifier,
  [912] = 1,
    ACTIONS(120), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_identifier,
  [918] = 3,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      sym_identifier,
    STATE(54), 1,
      sym_string,
  [928] = 1,
    ACTIONS(124), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_identifier,
  [934] = 1,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_identifier,
  [940] = 3,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_function_call_repeat1,
  [950] = 1,
    ACTIONS(130), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_identifier,
  [956] = 1,
    ACTIONS(132), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_identifier,
  [962] = 3,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_function_call_repeat1,
  [972] = 2,
    ACTIONS(137), 1,
      anon_sym_EQ,
    ACTIONS(139), 1,
      anon_sym_COLON,
  [979] = 1,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
  [983] = 1,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
  [987] = 1,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
  [991] = 1,
    ACTIONS(147), 1,
      sym_identifier,
  [995] = 1,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
  [999] = 1,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
  [1003] = 1,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
  [1007] = 1,
    ACTIONS(155), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 47,
  [SMALL_STATE(5)] = 71,
  [SMALL_STATE(6)] = 93,
  [SMALL_STATE(7)] = 115,
  [SMALL_STATE(8)] = 137,
  [SMALL_STATE(9)] = 159,
  [SMALL_STATE(10)] = 181,
  [SMALL_STATE(11)] = 211,
  [SMALL_STATE(12)] = 233,
  [SMALL_STATE(13)] = 261,
  [SMALL_STATE(14)] = 287,
  [SMALL_STATE(15)] = 313,
  [SMALL_STATE(16)] = 335,
  [SMALL_STATE(17)] = 357,
  [SMALL_STATE(18)] = 392,
  [SMALL_STATE(19)] = 424,
  [SMALL_STATE(20)] = 456,
  [SMALL_STATE(21)] = 488,
  [SMALL_STATE(22)] = 520,
  [SMALL_STATE(23)] = 552,
  [SMALL_STATE(24)] = 584,
  [SMALL_STATE(25)] = 618,
  [SMALL_STATE(26)] = 650,
  [SMALL_STATE(27)] = 682,
  [SMALL_STATE(28)] = 712,
  [SMALL_STATE(29)] = 744,
  [SMALL_STATE(30)] = 773,
  [SMALL_STATE(31)] = 801,
  [SMALL_STATE(32)] = 822,
  [SMALL_STATE(33)] = 840,
  [SMALL_STATE(34)] = 858,
  [SMALL_STATE(35)] = 873,
  [SMALL_STATE(36)] = 884,
  [SMALL_STATE(37)] = 895,
  [SMALL_STATE(38)] = 906,
  [SMALL_STATE(39)] = 912,
  [SMALL_STATE(40)] = 918,
  [SMALL_STATE(41)] = 928,
  [SMALL_STATE(42)] = 934,
  [SMALL_STATE(43)] = 940,
  [SMALL_STATE(44)] = 950,
  [SMALL_STATE(45)] = 956,
  [SMALL_STATE(46)] = 962,
  [SMALL_STATE(47)] = 972,
  [SMALL_STATE(48)] = 979,
  [SMALL_STATE(49)] = 983,
  [SMALL_STATE(50)] = 987,
  [SMALL_STATE(51)] = 991,
  [SMALL_STATE(52)] = 995,
  [SMALL_STATE(53)] = 999,
  [SMALL_STATE(54)] = 1003,
  [SMALL_STATE(55)] = 1007,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 4),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 4),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 5),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 4),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 4),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 4),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 4),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 2),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_def, 4, 0, 7),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_def, 4, 0, 6),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference_def, 4, 0, 8),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [145] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_costforecast(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
